#pragma once

#ifndef SCL_KEEP_DETECT_MACROS
	#undef SCL_UPLATFORM_WIN32
	#undef SCL_UPLATFORM_WIN64
	#undef SCL_UPLATFORM_WINDOWS

	#undef SCL_UPLATFORM_ANDROID
	#undef SCL_UPLATFORM_APPLE
	#undef SCL_UPLATFORM_IOS
	#undef SCL_UPLATFORM_LINUX
	#undef SCL_UPLATFORM_UNIX
#endif