#pragma once

#ifndef SCL_KEEP_DETECT_MACROS
	#undef SCL_PLATFORM_WIN64
	#undef SCL_PLATFORM_WIN32
	#undef SCL_PLATFORM_LINUX
	#undef SCL_PLATFORM_UNIX
	#undef SCL_PLATFORM_POSIX
	#undef SCL_PLATFORM_APPLE
	#undef SCL_PLATFORM_IOS_SIMULATOR
	#undef SCL_PLATFORM_IOS
	#undef SCL_PLATFORM_OSX
	#undef SCL_PLATFORM_MAC
	#undef SCL_PLATFORM_IPHONE
	#undef SCL_PLATFORM_ANDROID
#endif

